In [2]:
# ============================================================
# PART 0: LOAD AND PREPARE THE CLEANED FIVE-COUNTRY DATASET
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter

# Load the ONE cleaned CSV
df = pd.read_csv('datasets/fanta_5_countries_cleaned.csv')

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

Dataset Shape: (1059, 14)

Columns:
['code', 'product_name', 'brands', 'categories_tags', 'countries_tags', 'packaging_tags', 'stores', 'purchase_places', 'nutriscore_grade', 'nova_group', 'ecoscore_grade', 'ingredients_text', 'nutriments.sugars_100g', 'nutriments.energy-kcal_100g']

First 5 Rows:

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g
0,0024622511676,"Pepe's, Fantastico Chicharrones",Rudolph Foods Company Inc.,Unknown,united-states,Unknown,Unknown,Unknown,unknown,Unknown,unknown,"Pork fat with attached skin, salt.",Unknown,571.0
1,0035266007265,"Tastee, White Pretzel Wonder Fantasy",Tastee Apple Inc.,"plant-based-foods-and-beverages, plant-based-f...",united-states,Unknown,Unknown,Unknown,d,4.0,unknown,"Apple, caramel (corn syrup, sugar, condensed m...",28.57,232.0
2,0041321016141,Fantastico light cheese dressing,Bernstein's,"condiments, sauces, salad-dressings, groceries",united-states,Unknown,Unknown,Unknown,d,4.0,Unknown,"Water, distilled vinegar, soybean oil, salt, m...",3.23,80.65
3,0041497131815,Oriental Fantasy Mix,"Weis, Weis Markets Inc.",undefined,united-states,Unknown,Unknown,Unknown,d,3.0,Unknown,"ROASTED & SALTED (ALMONDS, SPANISH PEANUTS, CA...",12.7,1950.0
4,0481290024608,"Truffle Fantaisie Cacao Powdered Truffles, Plain",Alaus Mathez Chocolatier,Unknown,united-states,Unknown,Unknown,Unknown,unknown,4.0,unknown,"Vegetable fats (coconut, palm kernel), sugar, ...",42.5,575.0

In [3]:
# ============================================================
# CHECK COUNTRY DISTRIBUTION
# ============================================================

print("Country Distribution:")
display(df["countries_tags"].value_counts())

print("\nCountry Percentage:")
country_percentage = (
    df["countries_tags"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

display(country_percentage)

Country Distribution:

countries_tags
united-states     435
italy             315
united-kingdom    143
australia          95
romania            71
Name: count, dtype: int64

Country Percentage:

countries_tags
united-states     41.08
italy             29.75
united-kingdom    13.50
australia          8.97
romania            6.70
Name: proportion, dtype: float64

In [4]:
# ============================================================
# NUMERIC COLUMNS
# ============================================================

numeric_columns = [
    "nova_group",
    "nutriments.sugars_100g",
    "nutriments.energy-kcal_100g"
]

for col in numeric_columns:
    df[col + "_num"] = pd.to_numeric(df[col], errors="coerce")

print("Numeric analytical columns created:")
display(df[
    [
        "nova_group_num",
        "nutriments.sugars_100g_num",
        "nutriments.energy-kcal_100g_num"
    ]
].head())

Numeric analytical columns created:

   nova_group_num  nutriments.sugars_100g_num  nutriments.energy-kcal_100g_num
0             NaN                         NaN                           571.00
1             4.0                       28.57                           232.00
2             4.0                        3.23                            80.65
3             3.0                       12.70                          1950.00
4             4.0                       42.50                           575.00

PART 1 — 🇺🇸 UNITED STATES ANALYSIS

In [7]:
# ============================================================
# PART 1: UNITED STATES ANALYSIS
# ============================================================

us_df = df[df["countries_tags"] == "united-states"].copy()

print("UNITED STATES DATASET")
print("=" * 60)

print("Number of Records:", len(us_df))
print("Number of Attributes:", len(us_df.columns))

display(us_df.head())

UNITED STATES DATASET
============================================================
Number of Records: 435
Number of Attributes: 17

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nova_group_num,nutriments.sugars_100g_num,nutriments.energy-kcal_100g_num
0,0024622511676,"Pepe's, Fantastico Chicharrones",Rudolph Foods Company Inc.,Unknown,united-states,Unknown,Unknown,Unknown,unknown,Unknown,unknown,"Pork fat with attached skin, salt.",Unknown,571.0,NaN,NaN,571.00
1,0035266007265,"Tastee, White Pretzel Wonder Fantasy",Tastee Apple Inc.,"plant-based-foods-and-beverages, plant-based-f...",united-states,Unknown,Unknown,Unknown,d,4.0,unknown,"Apple, caramel (corn syrup, sugar, condensed m...",28.57,232.0,4.0,28.57,232.00
2,0041321016141,Fantastico light cheese dressing,Bernstein's,"condiments, sauces, salad-dressings, groceries",united-states,Unknown,Unknown,Unknown,d,4.0,Unknown,"Water, distilled vinegar, soybean oil, salt, m...",3.23,80.65,4.0,3.23,80.65
3,0041497131815,Oriental Fantasy Mix,"Weis, Weis Markets Inc.",undefined,united-states,Unknown,Unknown,Unknown,d,3.0,Unknown,"ROASTED & SALTED (ALMONDS, SPANISH PEANUTS, CA...",12.7,1950.0,3.0,12.70,1950.00
4,0481290024608,"Truffle Fantaisie Cacao Powdered Truffles, Plain",Alaus Mathez Chocolatier,Unknown,united-states,Unknown,Unknown,Unknown,unknown,4.0,unknown,"Vegetable fats (coconut, palm kernel), sugar, ...",42.5,575.0,4.0,42.50,575.00